package com.example.kineticsimulatorwebsocker;

import com.example.kineticsimulatorwebsocker.config.WebSocketProperties;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.scheduling.annotation.EnableScheduling;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableScheduling
@EnableConfigurationProperties(WebSocketProperties.class)
public class KineticSimulatorWebSockerApplication {

    public static void main(String[] args) {
        SpringApplication.run(KineticSimulatorWebSockerApplication.class, args);
    }

}
